repos:
  - repo: local
    hooks:
      - id: build-pdfs
        name: Build PDFs with pdflatex
        entry: bash -c "pdflatex CV_Malo_Leroy.tex && cd fr && pdflatex CV_Malo_Leroy.tex && cd .. && git add CV_Malo_Leroy.pdf fr/CV_Malo_Leroy.pdf"
        language: system
        pass_filenames: false
